export type CropInfo = {
  name: string
  localName: string
  scientificName: string
  type: "grain" | "pulse" | "oilseed" | "cash" | "vegetable" | "fruit" | "spice" | "plantation"
  growingSeason: string
  soilType: string
  waterRequirement: "low" | "medium" | "high"
  commonVarieties: string[]
  commonDiseases: string[]
  harvestingPeriod: string
  growingStates: string[]
  description: string
}

export const crops: Record<string, CropInfo> = {
  Rice: {
    name: "Rice",
    localName: "चावल (Chawal)",
    scientificName: "Oryza sativa",
    type: "grain",
    growingSeason: "Kharif (June-November)",
    soilType: "Clay loam, alluvial soil",
    waterRequirement: "high",
    commonVarieties: ["Basmati", "IR-64", "Pusa Basmati", "Sona Masoori", "BPT-5204"],
    commonDiseases: ["rice-blast", "rice-brown-spot", "rice-sheath-rot", "rice-blight"],
    harvestingPeriod: "110-150 days after sowing",
    growingStates: ["West Bengal", "Uttar Pradesh", "Punjab", "Tamil Nadu", "Andhra Pradesh", "Bihar", "Odisha"],
    description: "India is the second-largest rice producer in the world. Rice is the staple food for most Indians, grown primarily during the Kharif season with heavy rainfall.",
  },
  Wheat: {
    name: "Wheat",
    localName: "गेहूं (Gehun)",
    scientificName: "Triticum aestivum",
    type: "grain",
    growingSeason: "Rabi (October-April)",
    soilType: "Well-drained loamy soil",
    waterRequirement: "medium",
    commonVarieties: ["HD-2967", "PBW-343", "HD-3086", "DBW-187", "WH-1105"],
    commonDiseases: ["leaf-rust", "wheat-smut", "wheat-bunt"],
    harvestingPeriod: "130-150 days after sowing",
    growingStates: ["Uttar Pradesh", "Punjab", "Haryana", "Madhya Pradesh", "Rajasthan", "Bihar"],
    description: "India is the second-largest wheat producer globally. Wheat is the main Rabi crop, grown in the cool winter season across the northern plains.",
  },
  Maize: {
    name: "Maize",
    localName: "मक्का (Makka)",
    scientificName: "Zea mays",
    type: "grain",
    growingSeason: "Kharif (June-October) & Rabi",
    soilType: "Well-drained sandy loam to clay loam",
    waterRequirement: "medium",
    commonVarieties: ["Pioneer 3396", "NK-6240", "DKC-7074", "Ganga Safed-2", "HM-4"],
    commonDiseases: ["leaf-spot", "northern-blight", "leaf-rust"],
    harvestingPeriod: "90-110 days after sowing",
    growingStates: ["Andhra Pradesh", "Karnataka", "Rajasthan", "Maharashtra", "Bihar", "Uttar Pradesh"],
    description: "Maize is a versatile crop used as food, feed, and industrial raw material. It's grown in both Kharif and Rabi seasons across India.",
  },
  Cotton: {
    name: "Cotton",
    localName: "कपास (Kapas)",
    scientificName: "Gossypium hirsutum",
    type: "cash",
    growingSeason: "Kharif (May-December)",
    soilType: "Black cotton soil, alluvial soil",
    waterRequirement: "medium",
    commonVarieties: ["Bt Cotton", "MCU-5", "Suvin", "DCH-32", "RCH-2"],
    commonDiseases: ["cotton-bollworm", "cotton-leaf-curl", "cotton-wilt", "bacterial-spot"],
    harvestingPeriod: "150-180 days after sowing",
    growingStates: ["Gujarat", "Maharashtra", "Telangana", "Andhra Pradesh", "Punjab", "Haryana", "Karnataka"],
    description: "India is the largest cotton producer globally. Cotton is a major cash crop supporting the textile industry across the country.",
  },
  Sugarcane: {
    name: "Sugarcane",
    localName: "गन्ना (Ganna)",
    scientificName: "Saccharum officinarum",
    type: "cash",
    growingSeason: "Year-round (planted Sep-Oct & Jan-Mar)",
    soilType: "Deep well-drained loamy soil",
    waterRequirement: "high",
    commonVarieties: ["Co-0238", "Co-86032", "Co-05011", "Co-62175", "CoJ-64"],
    commonDiseases: ["sugarcane-red-rot", "sugarcane-smut", "sugarcane-wilt"],
    harvestingPeriod: "10-14 months after planting",
    growingStates: ["Uttar Pradesh", "Maharashtra", "Karnataka", "Tamil Nadu", "Bihar", "Punjab", "Haryana"],
    description: "India is the second-largest sugarcane producer. It's the primary source of sugar, jaggery, and ethanol production.",
  },
  Groundnut: {
    name: "Groundnut",
    localName: "मूंगफली (Moongfali)",
    scientificName: "Arachis hypogaea",
    type: "oilseed",
    growingSeason: "Kharif (June-October) & Rabi",
    soilType: "Sandy loam, well-drained soil",
    waterRequirement: "medium",
    commonVarieties: ["TAG-24", "GG-2", "JL-24", "Kadiri-6", "ICGV-91114"],
    commonDiseases: ["leaf-spot", "leaf-rust", "groundnut-stem-rot"],
    harvestingPeriod: "100-130 days after sowing",
    growingStates: ["Gujarat", "Andhra Pradesh", "Tamil Nadu", "Karnataka", "Rajasthan", "Maharashtra"],
    description: "India is the second-largest groundnut producer. It's a key oilseed crop, with kernels used for oil extraction and direct consumption.",
  },
  Onion: {
    name: "Onion",
    localName: "प्याज (Pyaaz)",
    scientificName: "Allium cepa",
    type: "vegetable",
    growingSeason: "Rabi (October-March) & Kharif",
    soilType: "Well-drained loamy soil",
    waterRequirement: "medium",
    commonVarieties: ["Nasik Red", "Bellary", "Pusa Red", "Agrifound Light Red", "N-53"],
    commonDiseases: ["onion-purple-blotch", "onion-downy-mildew", "onion-blight"],
    harvestingPeriod: "100-140 days after sowing",
    growingStates: ["Maharashtra", "Karnataka", "Madhya Pradesh", "Gujarat", "Bihar", "Rajasthan"],
    description: "India is the second-largest onion producer. Onion is a staple kitchen vegetable used daily across all Indian cuisines.",
  },
  Mango: {
    name: "Mango",
    localName: "आम (Aam)",
    scientificName: "Mangifera indica",
    type: "fruit",
    growingSeason: "Year-round (fruit set Feb-Mar, harvest Apr-Jul)",
    soilType: "Well-drained loamy soil, pH 5.5-7.5",
    waterRequirement: "medium",
    commonVarieties: ["Alphonso", "Kesar", "Dasheri", "Langra", "Chaunsa", "Totapuri", "Banginapalli"],
    commonDiseases: ["mango-anthracnose", "powdery-mildew", "mango-black-spot"],
    harvestingPeriod: "90-150 days after flowering",
    growingStates: ["Uttar Pradesh", "Andhra Pradesh", "Telangana", "Karnataka", "Maharashtra", "Tamil Nadu", "Gujarat"],
    description: "India is the largest mango producer, accounting for over 40% of global production. Mango is the national fruit of India.",
  },
  Banana: {
    name: "Banana",
    localName: "केला (Kela)",
    scientificName: "Musa paradisiaca",
    type: "fruit",
    growingSeason: "Year-round",
    soilType: "Deep rich loamy soil, pH 6-7.5",
    waterRequirement: "high",
    commonVarieties: ["Robusta", "Grand Naine", "Dwarf Cavendish", "Poovan", "Nendran", "Red Banana"],
    commonDiseases: ["banana-panama-wilt", "banana-sigatoka", "banana-bunchy-top"],
    harvestingPeriod: "11-14 months after planting",
    growingStates: ["Tamil Nadu", "Maharashtra", "Gujarat", "Andhra Pradesh", "Karnataka", "Madhya Pradesh"],
    description: "India is the largest banana producer globally. Banana is a year-round fruit crop grown extensively in tropical regions.",
  },
  Tomato: {
    name: "Tomato",
    localName: "टमाटर (Tamatar)",
    scientificName: "Solanum lycopersicum",
    type: "vegetable",
    growingSeason: "Year-round (depending on region)",
    soilType: "Well-drained loamy soil, pH 6-7",
    waterRequirement: "medium",
    commonVarieties: ["Arka Vikas", "Pusa Ruby", "Rashmi", "Vaibhav", "Abhinav"],
    commonDiseases: ["early-blight", "late-blight", "bacterial-spot", "leaf-mold", "septoria-spot", "spider-mites", "target-spot", "yellow-leaf-curl", "mosaic-virus"],
    harvestingPeriod: "60-90 days after transplanting",
    growingStates: ["Andhra Pradesh", "Madhya Pradesh", "Karnataka", "Odisha", "Gujarat", "Maharashtra", "Tamil Nadu"],
    description: "India is the second-largest tomato producer. Tomato is a versatile vegetable used in daily cooking across all Indian cuisines.",
  },
  Potato: {
    name: "Potato",
    localName: "आलू (Aloo)",
    scientificName: "Solanum tuberosum",
    type: "vegetable",
    growingSeason: "Rabi (October-March)",
    soilType: "Well-drained sandy loam",
    waterRequirement: "medium",
    commonVarieties: ["Kufri Jyoti", "Kufri Pukhraj", "Kufri Chandramukhi", "Kufri Bahar", "Kufri Himalini"],
    commonDiseases: ["early-blight", "late-blight", "bacterial-spot"],
    harvestingPeriod: "70-120 days after planting",
    growingStates: ["Uttar Pradesh", "West Bengal", "Punjab", "Bihar", "Gujarat", "Madhya Pradesh"],
    description: "India is the second-largest potato producer. Potato is a staple vegetable used extensively across Indian cooking.",
  },
  Brinjal: {
    name: "Brinjal",
    localName: "बैंगन (Baingan)",
    scientificName: "Solanum melongena",
    type: "vegetable",
    growingSeason: "Year-round",
    soilType: "Well-drained fertile loamy soil",
    waterRequirement: "medium",
    commonVarieties: ["Pusa Purple Long", "Pusa Purple Cluster", "Arka Shirish", "Bhagyamati", "Manjushree"],
    commonDiseases: ["bacterial-spot", "leaf-spot"],
    harvestingPeriod: "90-120 days after sowing",
    growingStates: ["Odisha", "West Bengal", "Gujarat", "Bihar", "Madhya Pradesh", "Andhra Pradesh"],
    description: "India is the second-largest brinjal producer. Brinjal is a common vegetable in Indian cuisine, used in curries and stuffed dishes.",
  },
  Okra: {
    name: "Okra",
    localName: "भिंडी (Bhindi)",
    scientificName: "Abelmoschus esculentus",
    type: "vegetable",
    growingSeason: "Summer (February-July) & Kharif",
    soilType: "Well-drained loamy soil",
    waterRequirement: "medium",
    commonVarieties: ["Pusa Sawani", "Arka Anamika", "Varsha Uphar", "Hybrid-8", "Kashi Pragati"],
    commonDiseases: ["leaf-spot", "yellow-leaf-curl"],
    harvestingPeriod: "50-70 days after sowing",
    growingStates: ["Uttar Pradesh", "Bihar", "West Bengal", "Odisha", "Assam", "Gujarat"],
    description: "Okra is a popular vegetable grown throughout India, valued for its tender green pods used in various dishes.",
  },
  Turmeric: {
    name: "Turmeric",
    localName: "हल्दी (Haldi)",
    scientificName: "Curcuma longa",
    type: "spice",
    growingSeason: "Kharif (April-August)",
    soilType: "Well-drained loamy or alluvial soil",
    waterRequirement: "medium",
    commonVarieties: ["Alleppey", "Erode", "Rajendra Sonia", "Narendra Haldi", "BSR-1", "Kasturi"],
    commonDiseases: ["leaf-spot", "leaf-blight"],
    harvestingPeriod: "7-9 months after planting",
    growingStates: ["Telangana", "Maharashtra", "Tamil Nadu", "Karnataka", "Andhra Pradesh", "Odisha"],
    description: "India is the largest turmeric producer and exporter. Turmeric is a sacred spice in Indian culture with medicinal and culinary uses.",
  },
  Ginger: {
    name: "Ginger",
    localName: "अदरक (Adrak)",
    scientificName: "Zingiber officinale",
    type: "spice",
    growingSeason: "Kharif (April-June)",
    soilType: "Well-drained loamy soil, pH 6-6.5",
    waterRequirement: "medium",
    commonVarieties: ["Rio de Janeiro", "Maran", "Himachal", "Nadia", "Vengurla"],
    commonDiseases: ["leaf-spot", "leaf-blight"],
    harvestingPeriod: "8-10 months after planting",
    growingStates: ["Karnataka", "Odisha", "Assam", "Madhya Pradesh", "West Bengal", "Gujarat"],
    description: "India is the largest ginger producer. Ginger is an essential ingredient in Indian cooking and traditional medicine.",
  },
  Chili: {
    name: "Chili",
    localName: "मिर्च (Mirch)",
    scientificName: "Capsicum annuum",
    type: "spice",
    growingSeason: "Kharif & Rabi",
    soilType: "Well-drained sandy loam to clay loam",
    waterRequirement: "medium",
    commonVarieties: ["Guntur Sannam", "Byadagi", "Kashmiri", "Jwala", "Ramnad Mundu"],
    commonDiseases: ["bacterial-spot", "powdery-mildew", "leaf-spot"],
    harvestingPeriod: "80-120 days after transplanting",
    growingStates: ["Andhra Pradesh", "Telangana", "Karnataka", "Maharashtra", "Madhya Pradesh", "Odisha"],
    description: "India is the largest chili producer globally. Indian chilies are renowned for their color, pungency, and variety worldwide.",
  },
  Coconut: {
    name: "Coconut",
    localName: "नारियल (Nariyal)",
    scientificName: "Cocos nucifera",
    type: "plantation",
    growingSeason: "Year-round",
    soilType: "Sandy loam, coastal alluvial soil",
    waterRequirement: "medium",
    commonVarieties: ["West Coast Tall", "East Coast Tall", "Dwarf Orange", "Malayan Dwarf", "Laccadive Micro"],
    commonDiseases: ["leaf-spot", "leaf-blight"],
    harvestingPeriod: "Year-round, 12-13 months per bunch",
    growingStates: ["Kerala", "Tamil Nadu", "Karnataka", "Andhra Pradesh", "Odisha", "West Bengal"],
    description: "India is the third-largest coconut producer. Coconut is integral to South Indian cuisine, culture, and daily life.",
  },
  Tea: {
    name: "Tea",
    localName: "चाय (Chai)",
    scientificName: "Camellia sinensis",
    type: "plantation",
    growingSeason: "Year-round (peak Apr-Oct)",
    soilType: "Well-drained acidic loamy soil, pH 4.5-5.5",
    waterRequirement: "high",
    commonVarieties: ["Assam", "Darjeeling", "Nilgiri", "Kangra", "Sikkim"],
    commonDiseases: ["leaf-spot", "leaf-blight"],
    harvestingPeriod: "Regular plucking every 7-14 days",
    growingStates: ["Assam", "West Bengal", "Tamil Nadu", "Kerala", "Himachal Pradesh", "Tripura"],
    description: "India is the second-largest tea producer. Tea is the most consumed beverage in India, with iconic varieties from Darjeeling and Assam.",
  },
  Coffee: {
    name: "Coffee",
    localName: "कॉफी (Coffee)",
    scientificName: "Coffea arabica / Coffea canephora",
    type: "plantation",
    growingSeason: "Year-round (harvest Oct-Feb)",
    soilType: "Well-drained loamy soil, pH 5.5-6.5",
    waterRequirement: "medium",
    commonVarieties: ["Arabica", "Robusta", "Kent", "S.795", "Cauvery"],
    commonDiseases: ["leaf-spot", "leaf-rust"],
    harvestingPeriod: "8-12 months after flowering",
    growingStates: ["Karnataka", "Kerala", "Tamil Nadu", "Andhra Pradesh", "Odisha"],
    description: "India produces both Arabica and Robusta coffee, primarily grown in the Western Ghats region. Indian coffee is known for its unique flavor profile.",
  },
  Mustard: {
    name: "Mustard",
    localName: "सरसों (Sarson)",
    scientificName: "Brassica juncea",
    type: "oilseed",
    growingSeason: "Rabi (October-March)",
    soilType: "Well-drained loamy soil",
    waterRequirement: "low",
    commonVarieties: ["Pusa Bold", "Varuna", "Kranti", "Pusa Mahak", "NRCHB-101"],
    commonDiseases: ["leaf-spot", "powdery-mildew", "leaf-blight"],
    harvestingPeriod: "100-150 days after sowing",
    growingStates: ["Rajasthan", "Haryana", "Uttar Pradesh", "Madhya Pradesh", "Gujarat", "West Bengal"],
    description: "India is the third-largest mustard producer. Mustard oil is widely used for cooking in northern and eastern India.",
  },
  Soybean: {
    name: "Soybean",
    localName: "सोयाबीन (Soyabean)",
    scientificName: "Glycine max",
    type: "oilseed",
    growingSeason: "Kharif (June-October)",
    soilType: "Well-drained sandy loam to clay loam",
    waterRequirement: "medium",
    commonVarieties: ["JS-335", "JS-9305", "NRC-37", "MAUS-71", "Pusa-9712"],
    commonDiseases: ["leaf-spot", "bacterial-spot"],
    harvestingPeriod: "95-120 days after sowing",
    growingStates: ["Madhya Pradesh", "Maharashtra", "Rajasthan", "Karnataka", "Telangana", "Chhattisgarh"],
    description: "Soybean is India's most important oilseed crop, primarily grown in central India. It's used for oil extraction and as a protein source.",
  },
  Pigeonpea: {
    name: "Pigeonpea",
    localName: "अरहर (Arhar)",
    scientificName: "Cajanus cajan",
    type: "pulse",
    growingSeason: "Kharif (June-November)",
    soilType: "Well-drained sandy loam to clay loam",
    waterRequirement: "low",
    commonVarieties: ["Pusa-9", "Maruti", "Asha", "Bahar", "Vaishali"],
    commonDiseases: ["leaf-spot", "leaf-blight"],
    harvestingPeriod: "140-200 days after sowing",
    growingStates: ["Maharashtra", "Karnataka", "Madhya Pradesh", "Uttar Pradesh", "Telangana", "Gujarat"],
    description: "Pigeonpea (Tur/Arhar) is a major pulse crop in India. It's a key source of protein in vegetarian diets, used to make dal.",
  },
  Chickpea: {
    name: "Chickpea",
    localName: "चना (Chana)",
    scientificName: "Cicer arietinum",
    type: "pulse",
    growingSeason: "Rabi (October-March)",
    soilType: "Well-drained sandy loam to clay loam",
    waterRequirement: "low",
    commonVarieties: ["Desi", "Kabuli", "JG-11", "JG-130", "Phule G-5"],
    commonDiseases: ["leaf-spot", "powdery-mildew"],
    harvestingPeriod: "100-150 days after sowing",
    growingStates: ["Madhya Pradesh", "Rajasthan", "Maharashtra", "Uttar Pradesh", "Karnataka", "Andhra Pradesh"],
    description: "India is the largest chickpea producer. Chickpea is a vital pulse used in various Indian dishes including chana masala and dal.",
  },
  Bajra: {
    name: "Bajra",
    localName: "बाजरा (Bajra)",
    scientificName: "Pennisetum glaucum",
    type: "grain",
    growingSeason: "Kharif (June-October)",
    soilType: "Sandy loam, well-drained",
    waterRequirement: "low",
    commonVarieties: ["HHB-67", "GHB-732", "RHB-177", "MH-2168", "Pusa-605"],
    commonDiseases: ["leaf-spot", "leaf-rust"],
    harvestingPeriod: "85-100 days after sowing",
    growingStates: ["Rajasthan", "Haryana", "Uttar Pradesh", "Gujarat", "Madhya Pradesh", "Maharashtra"],
    description: "Bajra (Pearl Millet) is a drought-resistant coarse grain crop grown in arid and semi-arid regions of India.",
  },
  Jowar: {
    name: "Jowar",
    localName: "ज्वार (Jowar)",
    scientificName: "Sorghum bicolor",
    type: "grain",
    growingSeason: "Kharif & Rabi",
    soilType: "Well-drained sandy loam",
    waterRequirement: "low",
    commonVarieties: ["CSH-16", "CSV-20", "M-35-1", "Phule Maulee", "Parbhani Moti"],
    commonDiseases: ["leaf-spot", "leaf-rust", "northern-blight"],
    harvestingPeriod: "100-130 days after sowing",
    growingStates: ["Maharashtra", "Karnataka", "Telangana", "Andhra Pradesh", "Madhya Pradesh", "Tamil Nadu"],
    description: "Jowar (Sorghum) is a drought-tolerant coarse grain used as food and fodder, primarily grown in the Deccan plateau.",
  },
  Cabbage: {
    name: "Cabbage",
    localName: "पत्ता गोभी (Patta Gobi)",
    scientificName: "Brassica oleracea",
    type: "vegetable",
    growingSeason: "Rabi (October-March)",
    soilType: "Well-drained fertile loamy soil",
    waterRequirement: "high",
    commonVarieties: ["Golden Acre", "Pusa Drumhead", "Pride of India", "K-1", "Green Express"],
    commonDiseases: ["leaf-spot", "leaf-blight"],
    harvestingPeriod: "70-100 days after transplanting",
    growingStates: ["Uttar Pradesh", "West Bengal", "Odisha", "Bihar", "Assam", "Karnataka"],
    description: "Cabbage is a popular winter vegetable grown extensively across India, used in curries, salads, and fermented preparations.",
  },
  Cauliflower: {
    name: "Cauliflower",
    localName: "फूल गोभी (Phool Gobi)",
    scientificName: "Brassica oleracea var. botrytis",
    type: "vegetable",
    growingSeason: "Rabi (September-March)",
    soilType: "Well-drained fertile loamy soil",
    waterRequirement: "high",
    commonVarieties: ["Pusa Snowball", "Kashi", "Pusa Deepali", "Pant Shubhra", "Aghani"],
    commonDiseases: ["leaf-spot", "leaf-blight"],
    harvestingPeriod: "80-120 days after transplanting",
    growingStates: ["Uttar Pradesh", "West Bengal", "Bihar", "Odisha", "Madhya Pradesh", "Haryana"],
    description: "Cauliflower is a widely grown winter vegetable in India, used in curries, pakoras, and as a rice substitute.",
  },
  Pomegranate: {
    name: "Pomegranate",
    localName: "अनार (Anar)",
    scientificName: "Punica granatum",
    type: "fruit",
    growingSeason: "Year-round (major harvest Sep-Nov)",
    soilType: "Well-drained sandy loam, pH 5.5-7",
    waterRequirement: "low",
    commonVarieties: ["Bhagwa", "Ganesh", "Ruby", "Mridula", "Arakta"],
    commonDiseases: ["leaf-spot", "bacterial-spot"],
    harvestingPeriod: "5-6 months after flowering",
    growingStates: ["Maharashtra", "Karnataka", "Gujarat", "Andhra Pradesh", "Telangana", "Tamil Nadu"],
    description: "India is the largest pomegranate producer. Pomegranate is valued for its sweet-tart arils and health benefits.",
  },
}

export function getCropInfo(name: string): CropInfo | undefined {
  return crops[name]
}

export function getCropsByType(type: CropInfo["type"]): CropInfo[] {
  return Object.values(crops).filter((c) => c.type === type)
}

export function getCropNames(): string[] {
  return Object.keys(crops)
}
